spring.application.name: gateway
server.port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring.cloud.gateway.routes:
- id: produto-route
  uri: lb://catalogo
  predicates:
    - Path=/produto/**

- id: categoria-route
  uri: lb://catalogo
  predicates:
    - Path=/categoria/**

- id: price
  uri: lb://price
  predicates:
    - Path=/price/**

- id: inventory-inventory
  uri: lb://inventory
  predicates:
    - Path=/inventory/**

- id: inventory-warehouse
  uri: lb://inventory
  predicates:
    - Path=/warehouse/**

- id: eureka-web-start
  uri: http://${app.eureka-server}:8761
  predicates:
    - Path=/eureka/web
  filters:
    - SetPath=/

- id: eureka-web-other
  uri: http://${app.eureka-server}:8761
  predicates:
    - Path=/eureka/**

app.eureka-server: discovery
---
spring.config.activate.on-profile: docker
app.eureka-server: discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/