spring.application.name: catalogo
server.port: 8084

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/catalogo
    username: topicos
    password: topicos

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

  #  cloud.stream:
  #    defaultBinder: rabbit
  #    default.contentType: application/json
  #    bindings.inventory-out-0:
  #      destination: inventory

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---

spring.config.activate.on-profile: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring.rabbitmq:
  host: message
  port: 5672
  username: guest
  password: guest

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/topicos-realm
